name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    # Crea variables reusables
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      IMAGE_NAME: 'oayala775/docker-graphql'
    steps:
      - name: Use checkout v4
        uses: actions/checkout@v4
        with:
          fetch_depth: 0 # Usa el último commit

      - name: Import and configure versioning
        uses: paulhatch/semantic-version@v5.4.0
        with:
          major_pattern: 'major:'
          minor_pattern: 'feat:'
          version_format: '${major}.${minor}.${patch}-prerelease${increment}'
        id: version

      # Paso para autenticarse en dockerhub
      - name: Authenticate on dockerhub
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # Construir la imagen
      - name: Build the Docker image
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME:$VERSION
          docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Push docker image to DockerHub
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: docker push $IMAGE_NAME:$VERSION

      - name: Push docker image to DockerHub as latest
        run: docker push $IMAGE_NAME
